baseURL = "https://opufubar.github.io/"
languageCode = "ja"
title = "大阪府立大学 プログラミングサークル OPU_Fu-Bar"

theme = "nix"

[menu]
  [[menu.header]]
    name = "Dialy"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about-us"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "member"
    weight = 2
    url = "/member"
  [[menu.header]]
    name = "document"
    weight = 3
    url = "/document"

[params]
  GithubID = "opufubar"
  TwitterID = "opu_fu_bar"
  GoogleplusID = "102636047177614888571"
  Name = "プログラミングサークル　Fu-Bar"
  HeaderUsername = "opu"
  HeaderHostname = "fu-bar"
  Email = "opu.fubar@gmail.com"
  About = "我々は大学では完全に教わることができず，実質，企業に就職してから学ぶことになっているプログラミングの技術を学生間で学び合い，スキルを高めることを目的としたサークルです．大阪府立大学の学生を中心に活動しています．"
  ProfilePicture = "/images/fubar-logo.png"
