baseURL = "https://opufubar.github.io/"
languageCode = "ja"
title = "大阪府立大学 教育系ITサークル OPU_Fu-Bar"
PaginatePath="/"
theme = "nix"

[menu]
  [[menu.header]]
    name = "dialy"
    weight = 1
    url = "/post"
  [[menu.header]]
    name = "about-us"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "member"
    weight = 2
    url = "/member"
  [[menu.header]]
    name = "product"
    weight = 3
    url = "/product"

[params]
  GithubID = "opufubar"
  TwitterID = "opu_fu_bar"
  GoogleplusID = "102636047177614888571"
  Slack = "opu.fubar"
  Name = "教育系ITサークル Fu-Bar"
  HeaderUsername = "opu"
  HeaderHostname = "fu-bar"
  Email = "opu.fubar@gmail.com"
  About = "大学では完全に教わることができず，実質，企業に就職してから学ぶことになっているプログラミングの技術を学生間で学び合い，スキルを高めることを目的としたサークルです．大阪府立大学の学生を中心に活動しています．興味がある方はお気軽にご連絡ください．"
  AboutAddress = "opu.fubar[at]gmail.com"
  ProfilePicture = "/image/fubar-logo.png"

[events]
  latest = "2017年7月4日(火): サークル説明会　(A6棟3階)"
